services:
  web:
    build: .
    command: fastapi run app --port 3333 --host 0.0.0.0 --reload
    volumes:
      - .:/app
    ports:
      - "3333:3333"
    environment:
      - ENVIRONMENT=development
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true