services:
  web:
    build: .
    command: fastapi run app --port 80 --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "80:80"
    environment:
      - ENVIRONMENT=development
    restart: unless-stopped
